12V - 48V DC/DC converter schematic
waterloo-rocketry/infrastructure pull request #15
Opened 2024-11-22 02:33 UTC by Hexamech

First draft of schematic completed with footprints.

2024-11-22 02:57 UTC, AshTheEngiqueer requested changes
1. Please don't commit the .lck file (kicad uses these to determine if the project is already open)
2. I assume you generated this design with TI WEBENCH? Please include the link to the design, as well as the input/output voltages and current limit in a text note.
3. You need to pick specific parts for the Inductor, N-MOSFET, and Diode. Also for the inductor, you'll need to find the corresponding footprint (good luck finding a standard footprint inductor)
4. Link datasheets to the boost chip, inductor, mosfet, and diode.
5. What's the purpose of the 1mR resistors on the input and output on the main sheet?
6. You probably don't need a second sheet to be honest - you can move some components closer together and put it all on one :)
7. Power symbols (12V) should point up, GND symbols point down. Also why is the output of your 48V connected to GND?
8. Your boost converter chip is missing the part number being visible, and you're missing a pin number on EP. 
9. You need connectors on the schematic (so we can connect the input and output to other boards).

2024-11-22 03:12 UTC, Pdada1 requested changes
1. You should add screw terminals for the board as symbols on the schematic
2. You should also fuse the output of the 48V output
3. You should add a inrush current limiter to stop the a large amount of current being drawn when the the board is initially connected

2024-12-30 03:20 UTC, AshTheEngiqueer commented
1. 
![image](https://github.com/user-attachments/assets/a20afc78-1163-4127-9422-27d90f1af917)
...why? why not just use the n-mosfet symbol? Also please link the actual datasheet rather than just the part number, and put the part number as a text note close to the mosfet.
2.
![image](https://github.com/user-attachments/assets/2c8886ef-35e1-453b-81e0-89ae78c650be)
These should be in parallel, not series.
3. Part numbers for the diode and inductor should also be text notes. Also your diode voltage doesnt match webench?
4. You'll need to source fuses for the input and output, and you should probably set your output fuse current limit to be less than the 2A maximum of the boost converter?

2025-01-14 22:17 UTC, AshTheEngiqueer requested changes
1. Somehow I didn't catch this last time, buck schematic wants 2x 4.7uF capacitors (in parallel) on the input line 
![image](https://github.com/user-attachments/assets/8b658378-da45-4e16-a35e-968d91ca6f5a)
2. this is kinda nitpicky but please rename your footprint library to something specific "12/48 boost" rather than "library" :)
3. please add the actual part number of the fuses to the schematic
4. thermistor should also get a part number in the schematic rather than the max current
5. I suspect we'll want to be able to put a voltage divider on the output of the boost converter so we can measure the output voltage - the best way to do that is to have two resistors in series marked DNP from the output to ground, and to add a screw terminal connected to the node between the two resistors.

2025-01-21 23:43 UTC, AshTheEngiqueer commented
![image](https://github.com/user-attachments/assets/30bf9e1f-899b-415e-bca7-7ad68a6d27c7)
I was meaning something like this, sorry if I was unclear. Also dont change the refdes of the dnp resistors, just write 'dnp' as their value/resistance

2025-01-21 23:55 UTC, AshTheEngiqueer commented
1. your mosfet footprint is wrong? usually there are 3 source pins and 4 drain pins (and the datasheet notes this as well) - make sure you downloaded the right footprint from digikey/snapEDA
2. some of these traces are too thin - kicad calculator says for a 2A trace with a 10C temperature rise you need a trace 0.7mm thick. Check the max current on both the +12V and +48V lines, and figure out what size they need to be. Not everything will need to be thick traces - ex. the decoupling capacitors can use the regular thin traces, but any path with a high current needs to be sufficiently thick.
3. I forgot to mention this but this will need mounting holes - probably M3? Those should be added to the schematic so the holes will get added to the pcb.
4. You can just throw a ground pour on both sides of the pcb

2025-02-02 01:58 UTC, Pdada1 requested changes, later dismissed
![image](https://github.com/user-attachments/assets/348f533f-9752-4662-b3d2-d06b26b5b1fb)
Just a note on foot prints for connectors. It's more useful to show what each terminal pin is connected to (12V, GND) then to label the connector as 12V Input. 
![image](https://github.com/user-attachments/assets/2c70687e-3af0-46c7-a697-504c1edb5314)
Should connect this other pin to GND

2025-02-02 03:05 UTC, Pdada1 commented
![image](https://github.com/user-attachments/assets/875d9505-bbb0-462a-b34e-2579bb1f0ff7)
Should delete stray traces. You can use the cleanup traces and vias tool to find them. 
![image](https://github.com/user-attachments/assets/f587deb0-46a5-4143-888e-d70c097acc37)
![image](https://github.com/user-attachments/assets/b59b38c3-eab1-436e-a9c3-34ef95347332)
Some of this layout is inefficient, you can make this trace line much shorter with something like this. 
![image](https://github.com/user-attachments/assets/38049807-b0bc-4ff3-a9b8-18f2a7dba63f)
Noticed a small trace on your fuse
In general you should clean up your layout since i'll affect the buck efficiency
![image](https://github.com/user-attachments/assets/12d0d44f-8cdb-48e9-b0d9-ef44cbfa628b)
![image](https://github.com/user-attachments/assets/8ffac2de-4fad-4fab-8e98-c7bf1e453fd7)
The datasheet has some example layouts you can use to condense the board and reduce trace length

2025-02-02 03:33 UTC, Pdada1 commented
![image](https://github.com/user-attachments/assets/385c1ecb-2cad-4e97-b022-e5e6fe0ac56c)
This via seems pointless

2025-03-24 00:00 UTC, StarlightDescender requested changes
1. Change the footprint for U1 so that the pad numbers match this: 
![image](https://github.com/user-attachments/assets/83f5a8d7-38fe-4c68-9743-8d245667c1a6)
also you'll want to change the symbol such that the pin numbers match this:
![image](https://github.com/user-attachments/assets/3a23f7a3-800b-4251-a92b-c8e7aa0293ee)
2. In general the layout is still kinda scuffed? what I would do is have the 12V input on one side, the 48V output on the other, and the current sensing terminals on either the top or bottom of the board. Also, some of your traces are super thick when they don't need to be (ex. both of the traces to the input current sense screw terminal can be pretty thin. If you'd like, I can go through this one with you some time in the next few days.
3. Some misc things - screw terminals should be at the edge of the board, and also you don't have any mounting holes?
4. There's a whole section on how to do the layout for the boost converter - section 12, which i've attached a screenshot of here. Refer to this when you do the boost converter layout.
![image](https://github.com/user-attachments/assets/02105af7-82ee-41e5-bb36-d01a1869f1a9)

2025-04-05 22:35 UTC, Pdada1 reviewed
![image](https://github.com/user-attachments/assets/ad40f39e-94c7-4782-b4a9-bbac8f4b8f53)
You can mark these resistors as DNP using the attribute 

Additionally a tip to make layout for the boost more efficient is to do the layout with only traces first (including gnd). That way you can see the actual pathing of the current loops and makes them easier to optimize compared to pours

2025-05-13 05:11 UTC, Pdada1 reviewed
![image](https://github.com/user-attachments/assets/b341c269-2543-4e72-9826-3544437de720)
Seems like a stray trace to me
![image](https://github.com/user-attachments/assets/f9a5ea72-2438-4483-b979-f7194e855756)
these power traces seem too thin to me. Trace calculator is recomending 12mm width at 15A, you only have 2mm or so. 
@JasonBrave @StarlightDescender we could probably order this board thicker in order to reduce the trace width size required. 
![image](https://github.com/user-attachments/assets/9b8d94cb-03c1-4ae1-9ca9-58417d568ddc)
The traces for the mosfet seem super thin. Like this is part of the main power path right when switched on
you should probably also edit the mosfet footprint to have all the pins assigned
![image](https://github.com/user-attachments/assets/f032da93-ad24-493d-8c77-bd93d828e7d4)
also looking at this diode and comparing it to the datasheet, pin 3 should be the diode output and both of the smaller pins are the diode input as far as I understand. it seems the pin assignemnt on this footprint is incorrect
![image](https://github.com/user-attachments/assets/6853d34b-5fd3-4192-be07-7ad4184b96ac)

2025-05-13 05:24 UTC, Pdada1 commented
![image](https://github.com/user-attachments/assets/309daefa-91bb-4916-8af4-228f858cc618)
This footprint also seems reversed?
![image](https://github.com/user-attachments/assets/cc2c0575-8ecf-49f2-9e3d-60278dd8e279)
on kicad
from the datasheet
![image](https://github.com/user-attachments/assets/ca9d0382-8191-43e6-899b-89f2439463bf)
it seems in the current setup the body diode of mosfet will conduct 😢

2025-05-13 05:24 UTC, Pdada1 commented
A combination of bad footprints are probably why this board ahs been so hard to layout.

2025-05-16 18:41 UTC, Hexamech commented
Pranav idk but it seems like that's an outdated version of the schematic or at least something seems weird about it but mine looks to be correct for a bunch of those things, I think I do need to make the board thicker though

2025-05-18 04:38 UTC, ihsan-sa commented
- Check all silkscreen labels as some are on pads/hidden/duplicate/on top of one another. (eg. J3).
- Might be safer to use bigger current sense resistors. I'm not sure it's the best idea to push all the current through an 0805 package, even if it isn't dissipating much power. I've often seen bigger packages used for this and it might be safer just for insurance purposes. Consider something like this (although this is prob overkill): 

![image](https://github.com/user-attachments/assets/6b03ec9c-b586-429c-bdb2-5117d351e54c)

- Consider adding thermal relief vias around pads of big components on big copper planes to make it easier to heat up and rework if needed.
- What is this extra trace on C5? Can your DITHOFF just connect to the C5 pad? Otherwise, you can make a small copper plane to clean this up.

![image](https://github.com/user-attachments/assets/53996da3-2b8d-4206-8c0b-fc956323b0fc)

- Decoupling caps on U1:
It might be a good idea to add smaller values to get rid of higher frequency noise. Adding a 100nF in parallel with the 1uF is pretty standard and should be fine.

- Confused by why these DNP resistors are needed. Are they placeholders for 0OHM jumpers? If they will carry current, I would suggest using a larger current as per previous point.

![image](https://github.com/user-attachments/assets/4b8bb696-4d79-4c66-8385-04862c1d7de5)

- Output capacitance:
I would recommend putting in smaller caps also. Maybe put in one or two 100nF, as well as one more 1uF or something. This will help reduce high frequency ripple. With boost converters, additional capacitance and large inductors are preferable.

- This doesn't really matter, but is there a way of increasing the thickness of the traces connecting these caps to the ground plane? Maybe use a trace and via to the plane if you can't change how the plane connects to the component.

![image](https://github.com/user-attachments/assets/fed555f2-eadd-434e-b5eb-38fb1710002e)

You can probably also this net a plane to connect all these components:

![image](https://github.com/user-attachments/assets/bca95562-9221-437d-8be4-58b366277339)

- R9 should also likely be bigger as a lot of current will be flowing through it when the MOSFET is on. See prev point about resistors in the power path.

![image](https://github.com/user-attachments/assets/102586d7-ceb1-4bec-9275-61144cf7dbcd)

- Q1: this package is likely going to be difficult to rework. It has a very big drain pad underneath the unit connected to a big copper area. Also, all the heat dissipation will be through the Q1 drain net copper plane and then through the dielectric and into the rest of the board. I would suggest using a THT package with a heat sink.

The same logic applies to D1, although that one might be easier to remove. 

Not sure we will be pushing this hard enough for thermals to be a problem, but just something to consider. In any case, I expect it might be tricky to remove Q1 if we ever need to though.

- Power traces seem thick enough. However, it wouldn't hurt to make them thicker wherever possible. For example, between J3 and J4.

- Here you have a ground plane with vias and also traces between the vias. You can remove the traces and make the copper area a bit bigger. 

![image](https://github.com/user-attachments/assets/12c89768-3369-4fcb-947f-2322968a3735)

- This trace in blue (48V output going to R10) does not need to be this thick. It will barely carry any current since it is a voltage sense path. Now, if you made this thick to reduce the resistance and improve the accuracy of the sensing, that is different. However, if that is the intent, you will probably get a much bigger improvement just by selecting higher tolerance resistors. 

![image](https://github.com/user-attachments/assets/6fa2b18b-b127-48d2-a1c8-a3428ff4db67)


- Ground planes: it would be a good idea to put vias at regular intervals and at the corners of ground planes. 
Also, is there a reason this entire section is cut off from the rest of the board ground plane? It is only connected via one trace.

![image](https://github.com/user-attachments/assets/7d30ac84-728c-45df-bf93-46233a646ce9)


Those are some of my initial ideas. Maybe we can talk about some of this. I'll have another look at some other stuff later as well. Let me know if you have any questions and if I'm wrong on anything!

2025-05-28 18:36 UTC, Joe-Joe-Joe-Joe commented
1. I dont think your INA180 on the 48V side will work. Common mode voltage is way out of spec
![image](https://github.com/user-attachments/assets/8159bf2e-f82b-4866-98d6-f73082cde661)
Use an INA290 or similar instead https://www.digikey.ca/en/products/detail/texas-instruments/INA290A3IDCKR/12762095
2. Schematic L
![image](https://github.com/user-attachments/assets/1310013c-0381-443c-95e6-6ddf26ca233a)
3. Webench is misbehaving so i cant verify the converter but 15A on the input? That implies like 53% efficiency at max draw which seems sus to me. This is the approximate efficiency curve from the datasheet
![image](https://github.com/user-attachments/assets/dc4dfaeb-81ca-4f16-8986-dbcba82444d9)

2025-05-28 18:54 UTC, Joe-Joe-Joe-Joe commented
1. You cannot do vias in pads (which need to be filled and capped) without some special settings through JLC. I think minimum is 6 layers. Just avoid it. running the surrounding ground pad into thermal vias is almost certainly sufficient.
![image](https://github.com/user-attachments/assets/88641076-ad79-4801-bacf-e6dd2189e235)
2. Many silkscreen issues, mostly on the front. Thats sort of a last step to fix, though
![image](https://github.com/user-attachments/assets/0099ee1e-5043-4a97-93e2-d7f65556fbc7)
3. Please avoid SMD non-resettable non-replaceable fuses. Even for small currents. You can use either PTCs or if you need to make sure it doesnt reset, we have these SMD fuse holder things on (i think) rocket power board you can check out.
![image](https://github.com/user-attachments/assets/bf4dc181-e1c2-4846-95b5-e2427ec6f183)

I think Ihsan hit most of the important points about layout for power

2025-06-01 16:07 UTC, StarlightDescender submitted a review, later dismissed
- please revert your changes to converters.kicad_pro and connectors.kicad_pro
- your board size is a bit weird, our normal is that the center to center distance of the mounting holes is some multiple of 0.5in
- dimensions shouldnt be on the copper layer
- refdes for C8-C10 are really small, please make them the standard size
- lots of daisy chaining through Q1

2025-06-03 19:15 UTC, Hexamech commented
Quick questions:
Regarding the fuses the reason its 15A was from some discussions a while back, but its also just a generic car fuse holder so it's easy to change. Its a quick blow on the 15A, but do you think something like 11-12A would be more fitting?

What daisy chaining through Q1?

2025-06-03 23:21 UTC, Joe-Joe-Joe-Joe commented
> Also how best can I un-commit the converters and connectors changes?

` git checkout master ground-side-power/*`

2025-06-03 23:25 UTC, Joe-Joe-Joe-Joe commented
I suppose 15A is acceptable given you are practically limited to 5A increments, and 10A is pushing it (8.3A is nominal at max output draw). Doesn't really matter from a manufacturing perspective since its a standard holder anyway

2025-06-03 23:28 UTC, Joe-Joe-Joe-Joe commented
Q1 daisy chaining is fake

You should also delete the .zip file you added, and then export the production files. Use the JLCPCB toolkit plugin for KiCAD, which exports everything in the correct format automatically. And plot the schematic to PDF. Schematic and layout otherwise LGTM

2025-06-08 22:00 UTC, StarlightDescender commented
please don't daisychain the decoupling capacitors - if one of the pads die, the line getting more noisy sucks (because no more camp) but when they're daisychained we just straight up lose the 12V in or 5V out. 
![image](https://github.com/user-attachments/assets/24dab71f-d5cb-434c-a61f-935575b8c0e7)
also GND is straight up not connected?

silkscreen could use some tidying up, some stuff is inconsistent orientations or overlapping with vias or etc.

2025-06-08 23:52 UTC, Joe-Joe-Joe-Joe commented
1. This is input current. It and the output current sense labels are both sideways
![image](https://github.com/user-attachments/assets/3ceba0c0-0102-49ba-87d0-0c873ef89dcb)
2. Silkscreen here is mega confusing. This is one of those cases to violate the "all text must be pointed the same way" requirement
![image](https://github.com/user-attachments/assets/f8265ef0-0175-4cc6-8fff-95f3d8f29097)
smth like this
![image](https://github.com/user-attachments/assets/4c2c2c40-68a0-44b4-86cc-6157962ece11)
3. Layout of this current amp could be better. See datasheet
![image](https://github.com/user-attachments/assets/5fd9d024-8681-4d75-b7c4-d6facff24e0a)
![image](https://github.com/user-attachments/assets/812822ba-3071-4027-a55b-dd18418fb899)

2025-06-09 00:58 UTC, Joe-Joe-Joe-Joe approved these changes
LGTM

2025-06-09 23:35 UTC, rexblade21 approved these changes
LGTM. That is one heck of an inductor

2025-06-10 02:15 UTC, Pdada1 approved these changes
LGTM

2025-06-10 02:38 UTC, merged